theme: minimal
title: System informacji przestrzennej projektu morskiej farmy wiatrowej
description: Portal zawiera prototyp mapy interaktywnej prezentującej przykładowe wdrożenie systemu informacji przestrzennej agregującego dane dla zespołu technicznego dewelopera.
